########## Testcase 0: Failed ##########
Expected Output: 
Alice

Your Output: 
Traceback (most recent call last):
  File "Dice.py", line 28, in <module>
    main()
  File "Dice.py", line 24, in main
    ans = list(key,val)
TypeError: list() takes at most 1 argument (2 given)
----------------------------------------

########## Testcase 1: Failed ##########
Expected Output: 
Mark

Your Output: 
Traceback (most recent call last):
  File "Dice.py", line 28, in <module>
    main()
  File "Dice.py", line 24, in main
    ans = list(key,val)
TypeError: list() takes at most 1 argument (2 given)
----------------------------------------

########## Testcase 2: Failed ##########
Expected Output: 
Bob

Your Output: 
Traceback (most recent call last):
  File "Dice.py", line 28, in <module>
    main()
  File "Dice.py", line 24, in main
    ans = list(key,val)
TypeError: list() takes at most 1 argument (2 given)
----------------------------------------

